- consumer:
    name: rabbitmq
    config:
      host: amqp://guest:guest@rabbitmq:5672/
      queue_name: users
  processors:
    - name: rabbitmq_default
    - name: rabbitmq_normalizer
  storages:
    - type: elasticsearch
      config:
        addresses:
          - http://elasticsearch:9200
